version: "3.8"

services:
  agent_b:
    build: ./agent_b
    container_name: agent_b
    ports:
      - "8000:8000"
    networks:
      - OutMessage_network
    
  agent_a:
    build: ./agent_a
    container_name: agent_a
    depends_on:
      - agent_b
      networks:
      - OutMessage_network
  tool_server:
    build: ./tool_server
    container_name: tool_server
    ports:
      - "5000:5000"
    networks:
      - OutMessage_network

networks:
  OutMessage_network:
    driver: bridge